version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKER_USER
          password: $DOCKER_ACCESS_TOKEN
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push application Docker image
          command: echo "Docker user:"
      - run:
          name: "echo environment variables from org-global context"
          command: echo $DOCKER_USER            -


workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context:
            - DockerHub
          filters:
            branches:
              only: master