version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push application Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker build -t danielbodart/portical:latest .
            docker push danielbodart/portical:latest


workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context:
            - dockerhub
          filters:
            branches:
              only: master